baseurl             = "https://asasmoyo.github.io/"
theme               = "cocoa"
contentdir          = "content"
languageCode        = "en-US"
layoutdir           = "layouts"
publishdir          = "public"
author              = "Arba Sasmoyo"
title               = "Arba Sasmoyo"
pluralizelisttitles = false
pygmentsuseclasses  = true
builddrafts         = false
canonifyurls        = true
disqusshortname     = "asasmoyo-github-io"
googleAnalytics     = "UA-109033209-1"

[permalinks]
fixed = ":title/"
blog  = "blog/:slug/"

[params]
author                  = "Arba Sasmoyo"
selfintro               = ""
cachebuster             = true
dateform                = "Jan 2, 2006"
dateformfull            = "Mon Jan 2 2006 15:04:05 MST"
description             = "sharing is caring!"
avatar                  = "images/avatar.png"
faviconfile             = "img/leaf.ico"
progressively           = true
small_banner_logo       = false
latestpostcount         = 5
lang                    = "en"
i18n_flags              = false
share                   = true
linkedin                = "//linkedin.com/in/asasmoyo"
github                  = "//github.com/asasmoyo"
email                   = "arba[dot]sasmoyo[at]gmail[dot]com"
highlightjs             = true
highlightjslanguages    = ["go", "bash", "json"]

# custom params with custom code
googlewebmastercode     = "MCXYe34PeMl552P1PjzdNyQtO_yhX9mh9lbGHb5dMpY"
