baseurl = "https://asasmoyo.github.io"
languageCode = "en"
title = "relax, you're probably doing fine"
theme = "kiss"
disqusShortname = "asasmoyo-github-io"
googleAnalytics = "UA-109033209-1"
Paginate = 5 # Number of posts per page
enableRobotsTXT = true

[params.features]
disqusOnDemand = true  # Load Disqus comments on click

[params.rss]
includeContent = true # Includes whole content in rss
authorName = "Arba Sasmoyo" # Site author's full name
authorEmail = "arba.sasmoyo@gmail.com"

[params.info]
enableSocial = false # Adds OpenGraph and Twitter cards
homeTitle = "relax, you're probably doing fine" # Title for home page
poweredby = false # Adds powered by Hugo and Kiss below Copyright section
related = true # Includes related articles

[params.social]
github = "asasmoyo"
email = "arba.sasmoyo@gmail.com"
linkedin = "asasmoyo"
rss = "index.xml"

[params.social.config]
platforms = ["email","github","linkedin", "rss"]

[taxonomies]
tag = "tags"

[blackfriday]
hrefTargetBlank = true
