baseurl             = "https://asasmoyo.github.io/"
theme               = "cocoa"
contentdir          = "content"
languageCode        = "en-US"
layoutdir           = "layouts"
publishdir          = "public"
author              = "Arba Sasmoyo"
title               = "Arba Sasmoyo"
pluralizelisttitles = false
pygmentsuseclasses  = true
builddrafts         = false
canonifyurls        = true
disqusshortname     = "asasmoyo-github-io"
googleAnalytics     = "UA-62145924-10"

[permalinks]
fixed = ":title/"
blog  = "blog/:slug/"

[params]
author                  = "Arba Sasmoyo"
selfintro               = ""
cachebuster             = true
dateform                = "Jan 2, 2006"
dateformfull            = "Mon Jan 2 2006 15:04:05 MST"
description             = "sharing is caring!"
avatar                  = "images/avatar.png"
faviconfile             = "img/leaf.ico"
progressively           = true
small_banner_logo       = false
latestpostcount         = 5
lang                    = "en"
i18n_flags              = false
share                   = true
linkedin                = "//linkedin.com/in/asasmoyo"
github                  = "//github.com/asasmoyo"
email                   = "[first_name][dot][last_name][at]gmail[dot]com"
googlewebmastercode     = "cSBPpTkkb9PJXo-n7XDDpaBT8dY5fTu8KKt6YW7Ze4Y"
highlightjs             = true
highlightjslanguages    = ["go", "bash", "json"]

[params.colors]
identifier = "#527fc1f"
identifier_dark = "#1a3152"
trivial = "#6a7a8b"
foreground = "#181d2a"
background = "#f9f9f9"
background_dark = "#282a36"
code = "#87a5d2"
type = "#97d28b"
special = "#ffcb8d"
value = "#96c2d7"
statement = "#ff8e91"
